### ISSUE TITLE
Markdown or rST?

### ISSUE THREAD

**Issue by matin** [balanced/balanced-api#1]
Should the API specs for [Balanced](https://www.balancedpayments.com) be written in [GitHub Flavored Markdown](http://github.github.com/github-flavored-markdown/) or [reStructuredText](http://docutils.sourceforge.net/rst.html)?

In creating this repo, we were having an internal debate around whether we should use Markdown or rst. Balanced is a Python shop, and it's considerably easier for us to generate rst. That means it's also easier to ensure validation and consistancy. However, the specs are being written for GitHub, and Markdown is the standard on GitHub.

**Comment by mjallday** [comment]
http://www.sphinx-doc.org/en/stable/markdown.html

IT.
HAS.
BEEN.
SOLVED>

Sphinx FTW
