### ISSUE TITLE
Producing a 300 response when underwriting a merchant in a test marketplace shouldn't require the 'region' parameter

### ISSUE THREAD

**Issue by jrus** [balanced/balanced-api#241]
Currently, to simulate a `300` response (not enough info to validate the merchant) in a test marketplace, it’s possible to use `postal_code` '99999' and `region` 'EX' among the merchant details. But use of the `region` parameter is otherwise deprecated.

The API shouldn't force people to test with a deprecated parameter, and should trigger a 300 response in a test marketplace whenever the `postal_code` is '99999', even when the `region` parameter is missing.

**Comment by remear** [comment]
API 1.0 has been deprecated. Underwriting in API 1.1 functions differently and this is no longer applicable.
