### ISSUE TITLE
card-not-validated should be 400 or 402, not 409 status

### ISSUE THREAD

**Issue by jrus** [balanced/balanced-api#278]
The card-not-validated error, which occurs when trying to tokenize a card with an invalid number, can get hit from balanced.js, but balanced.js shouldn’t be getting logical errors.

https://github.com/balanced/balanced-api/blob/master/errors.rst#card-not-validated

I think this probably belongs as a 402 error ("banking error"), but 400 might also be appropriate.

**Comment by remear** [comment]
API 1.0 is deprecated. API 1.1 should return the following response:

```json
{
  "errors": [
    {
      "status": "Payment Required",
      "category_code": "card-declined",
      "additional": "This transaction was declined by the card issuer. Customer please call bank.",
      "status_code": 402,
      "category_type": "banking",
      "extras": {},
      "request_id": "OHMae1bbb1895e611e4ab7e0230f00c9248",
      "description": "R530: This transaction was declined by the card issuer. Customer please call bank. Your request id is OHMae1bbb1895e611e4ab7e0230f00c9248."
    }
  ]
}
```
