### ISSUE TITLE
Push money to a debit card

### ISSUE THREAD

**Issue by jkwade** [balanced/balanced-api#32]
It's higher friction to collect bank account information than a credit card number. It would be useful to be able to push money to a credit card to pay a merchant.

**Comment by antitoxic** [comment]
Guys, I couldn't find more info on push-to-card than this thread. At the push-to-card page (https://www.balancedpayments.com/push-to-card) it says it's in private beta. 

Main page says Balanced is helping out Stripe. Does it mean push-to-card will work in Stripe?

I'm trying to figure out whether it works for US-only or it can work internationally? Also whether which cards does it work with? Only Visa?
