### ISSUE TITLE
Allow Accounts to Maintain a Balance

### ISSUE THREAD

**Issue by mjallday** [balanced/balanced-api#33]
Currently payments must be made to a funding destination such as a bank account.

Customers have expressed interest in being able to create credits to accounts without the funds leaving the system. This would allow aggregation of credits to help reduce fees incurred.

**Comment by remear** [comment]
The implementation of transaction descriptors, Order, Account (API 1.1), and Settlement resources seem to have resolved most aspects of this issue. Please open new issues for specific feature requests you feel might not have been adequately addressed yet.
