### ISSUE TITLE
Recurring Payments (aka Subscriptions)

### ISSUE THREAD

**Issue by mjallday** [balanced/balanced-api#40]
- Could Balanced support recurring payments?
- Is anyone interested in this feature?
- Would it be useful to have these for credits as well as debits?

**Comment by chadwtaylor** [comment]
+1 Any lead on this?

**Comment by eadonj** [comment]
+1

**Comment by mazhar5012** [comment]
+1 for subscription billing and [recurring billing api] (https://github.com/mazhar5012/recurring-subscription-billing)

**Comment by taylorbrooks** [comment]
@mazhar5012 I think it's pretty safe to say this is not going to happen. :)
