### ISSUE TITLE
Missing card URI in card event types

### ISSUE THREAD

**Issue by joonim** [balanced/balanced-api#411]
as you can see from below response for card.invalidated and card.updated event, currently there is no card.URI. Please include the card URI. Thank you

https://docs.balancedpayments.com/current/api?language=bash#event-types

=============================================================
<pre>
{
  "occurred_at": "2013-10-11T21:38:21.857000Z",
  "entity": {
    "expiration_month": 12,
    "_type": "card",
    "hash": "fc4ccd5de54f42a5e75f76fbfde60948440c7a382ee7d21b2bc509ab9cfed788",
    "name": null,
    "expiration_year": 2020,
    "brand": "MasterCard",
    "card_type": "MASTERCARD",
    "_uris": {},
    "meta": {},
    "last_four": "5100"
  },
  "type": "card.invalidated",
  "uri": "/v1/events/EV73c9c64032bd11e3b529026ba7d31e6f",
  "id": "EV73c9c64032bd11e3b529026ba7d31e6f"
}
</pre>
=============================================================
<pre>
{
  "occurred_at": "2013-10-11T22:34:19.994000Z",
  "entity": {
    "expiration_month": 12,
    "_type": "card",
    "hash": "fc4ccd5de54f42a5e75f76fbfde60948440c7a382ee7d21b2bc509ab9cfed788",
    "name": null,
    "expiration_year": 2020,
    "brand": "MasterCard",
    "card_type": "MASTERCARD",
    "_uris": {},
    "meta": {},
    "last_four": "5100"
  },
  "type": "card.updated",
  "uri": "/v1/events/EV4511afae32c511e3b616026ba7f8ec28",
  "id": "EV4511afae32c511e3b616026ba7f8ec28"
}
</pre>

**Comment by remear** [comment]
API 1.0 is deprecated. If this is still occurring and inconvenient in API 1.1, let us know, provide an example, and we'll re-open the issue.
