### ISSUE TITLE
Webhooks to HTTPS Callback URLs Fail

### ISSUE THREAD

**Issue by remear** [balanced/balanced-api#429]

**Comment by mekarpeles** [comment]
Howdy @remear, I'm running into the same issue. I believe the issue may be that Balanced (as a client for issuing callbacks) does not support SNI (Server Name Identification). So if a consumer of the API which as setup a callback endpoint has several HTTPS websites running on the same SNI-enabled domain, the Balanced client accepts only the 1st https certificate offered by the consumer's web server. The solution is either to force clients to serve each HTTPS virtualhost on different IPs or (presumably, I could be wrong) for Balanced to support SNI via apache or nginx or whatever web-server they are using. 

http://nginx.org/en/docs/http/configuring_https_servers.html#name_based_https_servers

**Comment by mjallday** [comment]
@mekarpeles are you able to share the hostname that you're attempting to be called back to? if you can't give us that publicly, give us your marketplace id and we can look it up from there.

**Comment by mekarpeles** [comment]
@mjallday The marketplace is "hackerlist". I've sent additional info over email.
