### ISSUE TITLE
Business name fails to update after initial setup

### ISSUE THREAD

**Issue by mjallday** [balanced/balanced-api#526]
Originally reported on [the Balanced dashboard](https://github.com/balanced/balanced-dashboard/issues/1049).

1. Create with null `business_name` `curl https://api.balancedpayments.com/customers/      -H "Accept: application/vnd.api+json;revision=1.1"      -u ak-test-2ADpvITfpgBn8uBzEGsQ2bIgWaftUWiul:      -X POST`
1. Update `business_name` to "foo" `curl https://api.balancedpayments.com/customers/CU3TMHucU477l8DCN4W6ifMY      -H "Accept: application/vnd.api+json;revision=1.1"      -u ak-test-2ADpvITfpgBn8uBzEGsQ2bIgWaftUWiul:      -X PUT -d business_name="foo"`
1. Subsequent updates do not change `business_name` `curl https://api.balancedpayments.com/customers/CU3TMHucU477l8DCN4W6ifMY      -H "Accept: application/vnd.api+json;revision=1.1"      -u ak-test-2ADpvITfpgBn8uBzEGsQ2bIgWaftUWiul:      -X PUT -d business_name="bar`

**Comment by remear** [comment]
Running the steps above, ``business_name`` updated correctly with the newly-supplied value.
