### ISSUE TITLE
What about batching the payout for Orders automatically?

### ISSUE THREAD

**Issue by matin** [balanced/balanced-api#689]
#660 discusses the challenge is using Orders where a seller is supposed to receive many payouts. A marketplace would solve the problem by batching the payout, but Orders makes this more difficult. The problem is that Orders have no concept of batched payouts. Each Credit is associated to an individual ACH transfer. What if Balanced automatically batched the transfers on a daily basis based on the recipient and `appears_on_statement_as`?

The marketplace would only be invoiced for the one ACH transfer.

**Comment by remear** [comment]
Batch payouts from Orders can be done via Account and Settlements as implemented by https://github.com/balanced/balanced-api/pull/707

Nothing will be done automatically.

**Comment by matin** [comment]
@mahmoudimus what @remear said :smile:
