### ISSUE TITLE
Payouts via check

### ISSUE THREAD

**Issue by jkwade** [balanced/balanced-api#69]
Not all of our merchants have bank accounts / want to share that information. Could Balanced provide bill pay-style check issuing? If so how much would it cost?

**Comment by think19000** [comment]
Am having a problem with my lob account ..wish other site like LOB can i mail a check out

**Comment by leore** [comment]
@think19000 what problem are you having?

**Comment by think19000** [comment]
After the account verify am trying to put it on LIVE ENVIRONMENT ....i cant put it on LIVE ENVIRONMENT time me out ....can i send a check out with TEST ENVIRONMENT ??
