### ISSUE TITLE
Fix AVS Street match functionality  

### ISSUE THREAD

**Issue by rserna2010** [balanced/balanced-api#726]
AVS street match always fails.

**Comment by mjallday** [comment]
@kyungmin is this still the case?

**Comment by funnylookinhat** [comment]
This seems to be working for us - but I noticed yesterday that "avs_result" is often incorrect.  We have quite a few cards that are tokenized with an AVS street/zip match, but say that the street address is not verified.

```
"avs_street_match": "yes",'
"avs_postal_match": "yes",
"avs_result": "Postal code matches, but street address not verified.",
```

**Comment by msherry** [comment]
The descriptive text is incorrect. The individual fields are now correct.
