### ISSUE TITLE
Dispute Document API

### ISSUE THREAD

**Issue by kyungmin** [balanced/balanced-api#732]
Since the dispute portal launched, there have been lot of requests for an dispute document API, to avoid manual uploads:

https://github.com/balanced/balanced-api-private/issues/14
https://github.com/balanced/balanced-api-private/issues/24
https://github.com/balanced/balanced-api/issues/290#issuecomment-69085640

**Comment by remear** [comment]
https://github.com/balanced/balanced-api/pull/571
