### ISSUE TITLE
BankAccountVerification creation issues

### ISSUE THREAD

**Issue by etipton** [balanced/balanced-api#747]
We are occasionally getting unexpected errors of "There is already a verification pending for this bank account" despite not initiating a prior verification for this BankAccount from our system (or even a BankAccount with the same account number).

How does this system work? Is there any documentation on how exactly a "conflict" (aka a matching real-world bank account has already had verification amounts sent) is determined for the verification process?

In one case, even though we got a failure, the user did receive microdeposits with the description "RenterUp" (my company). But that was useless because there was no BankAccountVerification object in your system to try to confirm the amounts against (because the API call failed).

I'm happy to share specific details, but first thing's first... are you able to shed some light on how Balanced BankAccount objects are mapped to real-world bank accounts behind-the-scenes?

Thanks!

Eric

**Comment by mjallday** [comment]
It could be the same bank account (e.g. account and routing numbers) attached to another customer. This is a fraud prevention measure since you could otherwise create a million bank accounts verifications and send the account a non-trivial amount of money.

If that's not the case (and it sounds like you do not think it is from reading your question) then give us the fingerprint or ID of the bank account in question and we'll have a look at it.

I'm not sure how to describe the mapping to you, but if you can re-word that question we'll be happy to answer.

**Comment by etipton** [comment]
Thanks @mjallday!

Right, we don't have any records of a duplicate bank account (routing + account number) in our system.

Here's all the info that I sent to support (ticket number 21043 in that system):

---

A user in our system added their bank account credentials and we’d like to initiate the micro deposits for verification -- however, we got the error message: "There is already a verification pending for this bank account"

I’ve checked the logs on both ends and I don’t see where we have created a duplicate bank account in our Marketplace or anything like that.

This is the bank account: https://dashboard.balancedpayments.com/#/marketplaces/MP5NovNbGgWSQzRtT7HY8BcC/bank_accounts/BA2s09lhBsxSiM9IsolnKL1J

Any suggestions for how to deal with this scenario? Is this a bug on your end or something that we need to work around?

More details…

The user contacted us and said that he DID receive microdeposits from “RenterUp” - so although these requests failed, it does look like it caused the microdeposits to go through to his bank account. The amounts were $.30 and $.38.

Of course, since the API creation requests failed, there was no bank_account_verification object, so he was unable to verify using those amounts.

Here are the failure logs:

https://dashboard.balancedpayments.com/#/marketplaces/MP5NovNbGgWSQzRtT7HY8BcC/logs/OHM5c40bb34c06811e485a702b12035401b

https://dashboard.balancedpayments.com/#/marketplaces/MP5NovNbGgWSQzRtT7HY8BcC/logs/OHM00c544b6c06b11e48c5306429171ffad

**There are no success logs for creating a verification for this bank account record before that.**

**Note that since this time, I was able to re-initiate the process and the user has since verified the bank account, so please look at logs instead of the current status.**

One more thing that might be a red herring -- the user said "I did do a PayPal verification the same day so maybe that threw everything off."

Our users typically need to get everything set up as quickly as possible because they’re trying to pay rent in time, so fixing this bug would be extremely helpful for us!

Additionally, here's another case of this happening:

Here is where our system attempted to initiate the verification automatically:
https://dashboard.balancedpayments.com/#/marketplaces/MP5NovNbGgWSQzRtT7HY8BcC/logs/OHM3c8ea14ac22d11e484ce02b12035401b

Here is where I went in and triggered the error myself:

https://dashboard.balancedpayments.com/#/marketplaces/MP5NovNbGgWSQzRtT7HY8BcC/logs/OHMc33cd312c23011e485a702b12035401b

---

Thanks for taking a look.

Eric

**Comment by mjallday** [comment]
@etipton when I look at bank account BA2s09lhBsxSiM9IsolnKL1J I see a successfully verified authentication already associated to it and the amounts do not match the amounts you quote. 

this verification was created at 2015-3-3T23:40:49 UTC. does that ring any bells for you?

**Comment by etipton** [comment]
Right, that is more recent than the issue I'm talking about. That's what was meant by:

Note that since this time, I was able to re-initiate the process and the user has since verified the bank account, so please look at logs instead of the current status.

Not trying to be "snarky"! Just making sure I'm being clear on everything.

**Comment by etipton** [comment]
A couple updates on my end:

I still can't trigger the verification process for BA1xtQJcDXKUiTdgXZHDAyYG and I see nothing on my end to indicate why.

I also have this case...

This user: https://dashboard.balancedpayments.com/#/marketplaces/MP5NovNbGgWSQzRtT7HY8BcC/customers/CU6XT1i6Plx8ZK6AWLtqTg2C

added one bank account, then must've thought the routing number was no good, so he went in and created a new bank account using a different routing number. Now the second bank account he added is not allowing verification. He used the same account number for both. This was one reason I was asking about how the system knows that two BankAccount records are actually the same real-world bank account.

---

Really appreciate you guys continuing to look into this. As far as urgency, these users are tenants who were trying to get set up in time to pay their rents to their landlord. They have all arranged other means to pay for March, so there is no extreme urgency at the moment, aside from avoiding customer support issues.

**Comment by mjallday** [comment]
@remear can you please investigate this issue?

**Comment by remear** [comment]
@etipton Would you please hop into IRC again so I can work directly with you.

**Comment by etipton** [comment]
@remear I'm a Balanced customer (not employee) - but I am happy to discuss over IM... eric@renterup.com (gchat)

**Comment by remear** [comment]
@etipton That's great! IRC is where we're able to help customer's one-on-one with technical issues, in private as well. You can join the room by navigating to http://webchat.freenode.net/?channels=balanced&uio=MTE9OTIaf

**Comment by etipton** [comment]
Correction! The user in my last comment is actually this one:

https://dashboard.balancedpayments.com/#/marketplaces/MP5NovNbGgWSQzRtT7HY8BcC/customers/CU37SqHEXxW0Xnbh1eO1PioT

Sorry about that!

**Comment by MID4D881527** [comment]
Payout funding support bank account
Datuch bangla bank ltd swift coad DBBLBDDH account nambur 01011030370502
